#!/bin/sh
######################################################################################################
#                                                                                                    #
# Autor: Jean Zonta                                                                                  #
# Pseudonym: wiki.anon                                                                               #
# Script Name: buildfox                                                                              #
# License: GNU/GPL V3                                                                                #
# DateTime: qui 15 mar 2018 09:42:13                                                                 #
# echo "}oqo4gtutF_gnuu4ius4hx" | perl -pe \ 's/(.)/chr(ord($1)-2*3)/ge'                             #
# echo 'comhttps://slackwarewww' | sed 's@\(com\)\(https://\)\(slackware\)\(www\)@\2\4.\3.\1 ..!!!@' #
#                                                                                                    #
######################################################################################################
if [ $(id -u) -ne 0 ]; then
  echo -e "\n\e[1;34m Usuário \e[1;31m${USER}\e[0m \e[1;34mnão é root\n faça login como root\n para executar o script\e[0m ..!!\n"
   exit
    else

TMP=${TMP:-/tmp}

BUILD=${BUILD:-1}

CWD=${CWD:-$(pwd)}

LANG_SYS=${LANG_SYS:-$(locale | grep "^LC_ALL" |cut -f2 -d = | cut -f1 -d. | sed 's/_/-/g')}

# Automatically determine the architecture we're building on:
if [ -z "${ARCH}" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i686 LIBDIRSUFFIX="" ;;
    x86_64) ARCH=x86_64 LIBDIRSUFFIX="64" ;;
  esac
fi

VERSION=${VERSION:-$(lftp -c "open http://download-installer.cdn.mozilla.net/ ; cd pub/firefox/releases/ ; ls" 2>/dev/null | egrep '50|60|70|80|90$' | sed -n '$p' | awk '{print $3}')}

#MOZILLA_URL=http://download-installer.cdn.mozilla.net/pub/firefox/releases/59.0b8/linux-x86_64/pt-BR/
MOZILLA_URL=${MOZILLA_URL:-http://download-installer.cdn.mozilla.net/pub/firefox/releases/${VERSION}/linux-${ARCH}/${LANG_SYS}/}

#FIREFOX_PKG=firefox-59.0b8.tar.bz2
FIREFOX_PKG=${FIREFOX_PKG:-$(lynx --dump ${MOZILLA_URL} | awk -F'/' '/^[ ]+[0-9]+.*\.tar\.bz2$/ {print $10}')}

#URL_PKG=http://download-installer.cdn.mozilla.net/pub/firefox/releases/59.0b8/linux-x86_64/pt-BR/firefox-59.0b8.tar.bz2
URL_PKG=${URL_PKG:-${MOZILLA_URL}${FIREFOX_PKG}}

PKG_NAME=${PKG_NAME:-${CWD}/${FIREFOX_PKG}}
#PKG_NAME=firefox-59.0b8.tar.bz2

MOZ=${MOZ:-${TMP}/$(echo ${FIREFOX_PKG} | cut -f1 -d-)}

#pkg name version
PRGNAM=${PRGNAM:-firefox-${VERSION}}

PKG=${PKG:-${TMP}/${PRGNAM}}

if [ -f ${PKG_NAME} ]; then 

echo "Ah, found it ${PKG_NAME} .!";

# Source file availability:
elif [ ! -f ${PKG_NAME} ]; then
  echo "Source '$(basename ${PKG_NAME})' not available yet..."
  # Check if the $CWD is writable at all - if not, download to ${PKG_NAME}
  [ -w "${CWD}" ] || ${PKG_NAME}
  
  if ! [ "x${URL_PKG}" == "x" ]; then
   echo "Will download file to $(dirname $PKG_NAME)"
    wget -nv -T 20 "${URL_PKG}" || true
     echo "Download complete."
    
    if [ $? -ne 0 -o ! -s "${PKG_NAME}" ]; then
     echo "Downloading '$(basename ${PKG_NAME})' failed... aborting the build."
      mv -f "${PKG_NAME}" "${PKG_NAME}".FAIL
       exit 1
    fi
  else
    echo "File '$(basename ${PKG_NAME})' not available... aborting the build."
     exit 1
  fi
fi

rm -rf ${MOZ}*

mkdir -p ${PKG}

mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}

mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/mozilla/plugins

mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${VERSION}

mkdir -p ${PKG}/usr/share/applications

mkdir -p ${PKG}/usr/share/icons

mkdir -p ${PKG}/usr/share/pixmaps

mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${VERSION}/chrome/icons/default

cp -ar ${CWD}/hicolor ${PKG}/usr/share/icons

cd ${TMP}

# Extract all packages tar,gz,tgz,tlz,xz,txz,bz2,tbz
tar xfk ${PKG_NAME} || exit 1

cp -ar ${MOZ}/* ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${VERSION}

mkdir ${PKG}/install

MODIFICA=${MODIFICA:-$(sed  -i '/lib64/ s/firefox-.*/firefox-'${VERSION}'\/firefox firefox )/g;' ${CWD}/doinst.sh)}


cat ${CWD}/doinst.sh >> ${PKG}/install/doinst.sh

cat ${CWD}/slack-desc >> ${PKG}/install/slack-desc

cat ${CWD}/buildfox >> ${PKG}/install/firefox.SlackBuild

cat ${CWD}/LICENSE >> ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${VERSION}/LICENSE

cat ${CWD}/mozilla-firefox.desktop >> ${PKG}/usr/share/applications/mozilla-firefox.desktop

cp -ar ${MOZ}/browser/chrome/icons/default/default16.png ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${VERSION}/chrome/icons/default

cd ${PKG}

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;

makepkg -l y -c n ../mozilla-firefox-${LANG_SYS}_${VERSION}-${ARCH}-${BUILD}.txz

mv  ../mozilla-firefox-${LANG_SYS}_${VERSION}-${ARCH}-${BUILD}.txz ${CWD}

rm -rf ${MOZ}*
rm -rf ${PKG_NAME}

fi