#!/bin/sh

LANG_SYS=${LANG_SYS:-$(locale | grep "^LC_ALL" |cut -f2 -d = | cut -f1 -d. | sed 's/_/-/g')}

# Substitute your own language:
PKGLANG=${PKGLANG:-${LANG_SYS}}

# Substitute your relese version:
VERSION=${VERSION:-56.0b9}

#pkg name version
PRGNAM=${PRGNAM:-firefox-$VERSION}

# Automatically determine the architecture we're building on:
if [ -z "${ARCH}" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i686 LIBDIRSUFFIX="" ;;
    x86_64) ARCH=x86_64 LIBDIRSUFFIX="64" ;;
  esac
fi

CWD=${CWD:-$(pwd)}
TMP=${TMP:-/tmp}
MOZ=${MOZ:-${TMP}/firefox}
PKG=${PKG:-${TMP}/${PRGNAM}}
# Where do we look for sources?
SRCDIR=${SRCDIR:-$(cd $(dirname $0); pwd)}

# Automatically determine the architecture we're building on:

SOURCE=${SOURCE:-${SRCDIR}/${PRGNAM}.tar.bz2}

URL_PKG=${URL_PKG:-http://download-installer.cdn.mozilla.net/pub/firefox/releases/${VERSION}/linux-${ARCH}/${PKGLANG}/${PRGNAM}.tar.bz2}

#URL_PKG=${URL_PKG:-https://ftp.mozilla.org/pub/firefox/releases/${VERSION}/linux-${ARCH}/${PKGLANG}/${PRGNAM}.tar.bz2}

if [ -f ${SOURCE} ]; then 

echo "Ah, found it ${SOURCE} .!";

# Source file availability:
elif [ ! -f ${SOURCE} ]; then
  echo "Source '$(basename ${SOURCE})' not available yet..."
  # Check if the $SRCDIR is writable at all - if not, download to $SOURCE
  [ -w "$SRCDIR" ] ||  SOURCE="$SRCDIR/$(basename $SOURCE)"
  
  if ! [ "x${URL_PKG}" == "x" ]; then
   echo "Will download file to $(dirname $SOURCE)"
    wget -nv -T 20 "${URL_PKG}" || true
     echo "Download complete."
    
    if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
     echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
      mv -f "${SOURCE}" "${SOURCE}".FAIL
       exit 1
    fi
  else
    echo "File '$(basename ${SOURCE})' not available... aborting the build."
     exit 1
  fi
fi

PKGVERSION=${PKGVERSION:-$(basename $(ls firefox-*.tar.?z* | cut -d - -f 2 | rev | cut -f 3- -d . | rev))}
RELEASEVER=${RELEASEVER:-$(echo ${PKGVERSION} | cut -f 1 -d r | cut -f 1 -d b | cut -f 1 -d e)}
BUILD=${BUILD:-1}

mkdir -p ${PKG}

mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}

mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/mozilla/plugins

mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${PKGVERSION}

mkdir -p ${PKG}/usr/share/applications

mkdir -p ${PKG}/usr/share/icons

mkdir -p ${PKG}/usr/share/pixmaps

mkdir -p ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${PKGVERSION}/chrome/icons/default

cp -ar ${CWD}/hicolor ${PKG}/usr/share/icons

cd ${TMP}

# Extract all packages tar,gz,tgz,tlz,xz,txz,bz2,tbz
tar xfk $CWD/firefox-${PKGVERSION}.tar.?z* || exit 1

cp -ar ${MOZ}/* ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${PKGVERSION}

mkdir ${PKG}/install

MODIFICA=${MODIFICA:-$(sed  -i '/lib64/ s/firefox-.*/firefox-'"$VERSION"'\/firefox firefox )/g;' doinst.sh)}

cp -ar ${CWD}/doinst.sh ${PKG}/install/

cp -ar ${CWD}/slack-desc ${PKG}/install/

cp -ar ${CWD}/LICENSE  ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${PKGVERSION}/

cp -ar ${CWD}/mozilla-firefox.desktop  ${PKG}/usr/share/applications/

cp -ar ${MOZ}/browser/chrome/icons/default/default16.png ${PKG}/usr/lib${LIBDIRSUFFIX}/firefox-${PKGVERSION}/chrome/icons/default

cd ${PKG}

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;

  makepkg -l y -c n ../mozilla-firefox-${PKGLANG}_${PKGVERSION}-${ARCH}-${BUILD}.txz

mv  ../mozilla-firefox-${PKGLANG}_${PKGVERSION}-${ARCH}-${BUILD}.txz ${CWD}