#!/bin/sh 

## Remove games of KDE

removepkg palapeli bomber granatier kblocks ksnakeduel kbounce kbreakout kgoldrunner kspaceduel kapman kolf kollision kpat lskat blinken khangman pairs ktuberling
removepkg kdiamond ksudoku kubrick picmi bovo kblackbox kfourinline kmahjongg kreversi ksquares kigo kiriki kshisen gnuchess katomic 
removepkg killbots klickety klines konquest ksirk knavalbattle kanagram amor kajongg kjumpingcube kmines knetwalk libkdegames libkdeedu

removepkg twm blackbox windowmaker fvwm xfce

## Remove kopote
removepkg kdenetwork kdenetwork-filesharing kdenetwork-strigi-analyzers kopete

## Remove nepomuk
removepkg nepomuk nepomuk-core nepomuk-widgets

## Remove akonadi
removepkg akonadi

## Remove gnome "packages"
removepkg gcr polkit-gnome gnome-themes gnome-keyring libgnome-keyring

## Remove others
removepkg seamonkey pidgin xchat dragon thunderbird kplayer calligra bluedevil blueman bluez bluez-firmware

removepkg xine-lib xine-ui vim-gvim vim sendmail sendmail-cf xpdf tetex tetex-doc kget
## Dolphin need baloo baloo-widgets
