#!/bin/bash

echo
echo "----------- Checking MySQL connection: ----------"
echo

dbaccess="denied"
until [[ $dbaccess = "success" ]]; do
read -p "Digite o nome de usuario: " usuario
read -p "Diite a senha do banco de dados: " senha

mysql --user="$usuario" --password="$senha" 2>/dev/null

#mysql --user="$1" --password="$2" -e exit 2>/dev/null
dbstatus=`echo $?`
if [ $dbstatus -ne 0 ]; then
echo
echo "MYSQL Error: please check the user access and try again!"
echo
exit
else
dbaccess="success"
echo "Connect Mysl Success!"
fi
done 
