#!/bin/bash

echo
echo "----------- Checking MySQL connection: ----------"
echo

dbaccess="denied"
until [[ $dbaccess = "success" ]]; do
mysql --user="$1" --password="$2" -e exit 2>/dev/null
dbstatus=`echo $?`
if [ $dbstatus -ne 0 ]; then
echo
echo "MYSQL Error: please check the user access and try again!"
echo
exit
else
dbaccess="success"
echo "Connect Mysl Success!"
fi
done 
